spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

config:
  version: dev_version_6
  
user:
  username: zhangsan6

---
spring:
  profiles: test

config:
  version: test_version

---
spring:
  profiles: pro

config:
  version: pro_version
